services:
  website:
    build: 
      context: .
      args:
        - DATABASE_URL=mysql://root:docker_password/database:3306/sygnmnt
    ports:
      - "3000"

  database:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=docker_password

  docker:
    image: docker:20
  

