services:
  website:
    command: bash ./scripts/wait-for-it.sh database:3306 -s -t 0 -- bash -c "docker pull gcc:4.9 && npx prisma db push && npm run start"
    image: ghcr.io/pepyta/sygnmnt:latest
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=mysql://root:mysql_password@database:3306/sygnmnt
      - JWT_SECRET_KEY=CHANGE_THIS_TO_SOMETHING_SECURE

  database:
    platform: linux/x86_64
    image: mysql
    restart: always
    expose:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
