services:
  database:
    container_name: database
    restart: unless-stopped
    image: mysql
    expose:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
  
  website:
    container_name: website
    command: bash -c "docker pull gcc:4.9 && chmod +x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh database:3306 -s -t 0 && npx prisma db push && npm run test"
    build: 
      context: .
      args:
        - JWT_SECRET_KEY=supersecret123
        - DATABASE_URL=mysql://root:mysql_password@database:3306/sygnmnt
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
