# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: CI/CD 

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # install gcc to have it on the disk befor running the tests
    # this is required because it would time out the runners
    - run: docker pull gcc:4.9
    - run: npm test
