name: publish
on:
  release:
    types: [published]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build . --tag ghcr.io/pepyta/sygnmnt:latest --tag ghcr.io/pepyta/sygnmnt:$(node -p "require('./package.json').version") --build-arg JWT_SECRET_KEY=supersecret123 --build-arg DATABASE_URL=mysql://root:mysql_password@database:3306/sygnmnt
    - name: Publish Docker image
      run: docker push ghcr.io/pepyta/sygnmnt:latest