name: publish
on:
  release:
    types: [published]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build . --tag ghcr.io/pepyta/sygnmnt:latest
    - name: Publish Docker image
      run: docker push ghcr.io/pepyta/sygnmnt:latest